- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: 20hrs
    TRAINER: siva
  tasks:
  - name: print the variables
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}"
  - name:  print the variables
    ansible.builtin.debug:
      msg: "course is {{ COURSE }},duration is {{ DURATION }}"   
