- name: variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the variables from file
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}" 