- name: condition
  hosts: local
  connection: local
  vars:
    my_number: 15
  tasks:
  - name: print if the number is greater than 10
    ansible.builtin.debug:
      msg: "given number {{ my_number }} is greater than 10"
    when: my_number > 10  


  - name: print if the number is less than or equal  10
    ansible.builtin.debug:
      msg: "given number {{ my_number }} is less than or equal 10"
    when: my_number <= 10  
