- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.bultin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "Redhat"  
 - name: install nginx
   ansible.bultin.apt:
     name: nginx
     state: installed
   when: ansible_os_family == "Debian"  