- name: install nginx
  hosts: all
  become: yes
  serial: 5
  tasks:
  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started    